### ISSUE TITLE
Implement Pre-Commit for Better Convention Checks and Testing

### ISSUE THREAD

**Issue by jjfrench** [MAAP-Project/maap-documentation-examples#22]
## Description
Pre-commit allows users to run hooks on every commit. Pre-commit provides hooks for templating commit messages as well as verifying them, this would work well with conventional commit message formats. Pre-commit can also hook linter like Black or customized hooks to run tests like doctests. Other useful hooks could be for linting other file types like yaml or terraform.

## Links
[Pre-commit documentation](https://pre-commit.com/index.html)
[Supported hooks](https://pre-commit.com/hooks.html)
[Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/#specification)
[#266](https://github.com/NASA-IMPACT/active-maap-sprint/issues/266) Create Unit Tests/File Restructuring for maap-documentation-examples Repository

## Example
```
repos:
  - repo: https://github.com/psf/black
    rev: v22.6.0
    hooks:
      - id: black
      - id: black-jupyter
  - repo: local
      hooks:
      - id: pytest
        name: pytest
        stages: [commit]
        types: [python]
        entry: pytest
        language: system
        pass_filenames: false
        always_run: true
```

## Acceptance Criteria
Pre-commit hooks for
- [ ] commit message format
- [ ] linting (black)
- [ ] ...
